name: ly_archlink
channels:
  - pytorch
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - numpy=1.23.5
  - pandas=1.5.3
  - scipy=1.10.1
  - scikit-learn=1.1.2
  - joblib=1.2.0
  - matplotlib=3.7.5
  - openpyxl=3.1.5
  - pyyaml
  - ruamel.yaml
  - biopython
  - tqdm
  - click
  - atomicwrites
  - python-igraph
  - leidenalg
  - pytorch
  - make
  - c-compiler
  - bedtools
  - samtools
  - pysam
  - checkm2
  - hmmer
  - prodigal
  - perl
  - pip
  - pip:
      - fair-esm
      - hnswlib
      - checkm-genome
      - biolib
