import os
import sys
import pickle
import numpy as np
import random  # Used for random sampling


# --- 1. Load Frequency Feature ---
def load_frequency_feature(filepath):
    """
    Load the frequency feature generated by 01.generate_frequency.py.
    Args:
        filepath (str): Path to the frequency feature file.
    Returns:
        dict: Frequency index {contig: {neighbor: frequency}}.
    """
    try:
        with open(filepath, 'rb') as f:
            freq_index = pickle.load(f)
        print(f"Loaded frequency feature file: {filepath}")
        return freq_index
    except FileNotFoundError:
        print(f"Error: Frequency feature file '{filepath}' not found.")
        return {}
    except Exception as e:
        print(f"Error reading frequency feature file: {e}")
        return {}


# --- 2. Normalization Function ---
def normalize_features(values):
    """
    Apply Min-Max normalization to a list of values.
    """
    valid = [v for v in values if v is not None]
    if not valid:
        return values

    min_val, max_val = min(valid), max(valid)
    if max_val == min_val:
        return [0.0 if v is not None else None for v in values]

    return [(v - min_val) / (max_val - min_val) if v is not None else None for v in values]


# --- Main Function ---
def main(args):
    b_feature_frequency_file = args.output_path + '/binning/frequency/frequency.pkl'
    output_feature_file = args.output_path + '/binning/s_cluster/combine_binning.pkl'

    print("\n--- Loading Frequency Feature ---")
    freq_index = load_frequency_feature(b_feature_frequency_file)

    # Print 3 random samples
    if freq_index:
        freq_keys = list(freq_index.keys())
        random_samples = random.sample(freq_keys, min(3, len(freq_keys)))
        for i, contig in enumerate(random_samples):
            print(f"\n--- Frequency Sample {i+1} ---")
            preview = dict(list(freq_index[contig].items())[:5])
            print(f"Contig: {contig}")
            print(f"Neighbor Frequencies: {preview} ...")
    else:
        print("Frequency dataset is empty.")
        sys.exit(1)

    # --- Extract all contig pairs ---
    all_pairs = set()
    for c1, neighbors in freq_index.items():
        for c2 in neighbors.keys():
            all_pairs.add(tuple(sorted((c1, c2))))

    print(f"\nTotal {len(all_pairs)} unique contig pairs extracted.")

    # --- Collect raw frequency values ---
    features = {}
    freq_values = []

    for contigA, contigB in all_pairs:
        freq_val = None

        if contigA in freq_index and contigB in freq_index[contigA]:
            freq_val = freq_index[contigA][contigB]
        elif contigB in freq_index and contigA in freq_index[contigB]:
            freq_val = freq_index[contigB][contigA]

        if freq_val is not None:
            freq_values.append(freq_val)

        features[(contigA, contigB)] = {'B_frequency': freq_val}

    # --- Normalize ---
    print("\n--- Normalizing Features ---")

    min_val, max_val = (min(freq_values), max(freq_values)) if freq_values else (None, None)

    normalized_features = {}
    for pair, vals in features.items():
        freq_val = vals['B_frequency']

        if freq_val is not None and min_val is not None and max_val is not None:
            norm_val = (freq_val - min_val) / (max_val - min_val) if max_val != min_val else 0.0
        else:
            norm_val = None

        normalized_features[pair] = {'B_frequency': norm_val}

    # --- Print 3 samples ---
    if normalized_features:
        pairs = list(normalized_features.keys())
        random_samples = random.sample(pairs, min(3, len(pairs)))
        for i, pair in enumerate(random_samples):
            print(f"\n--- Sample {i+1} ---")
            print(f"Contig Pair: {pair}")
            for k, v in normalized_features[pair].items():
                print(f"   {k}: {v}")

        print(f"\nTotal {len(normalized_features)} contig pairs will be saved.")
    else:
        print("Normalized dataset is empty.")
        sys.exit(1)

    # --- Save ---
    try:
        with open(output_feature_file, 'wb') as f:
            pickle.dump(normalized_features, f, protocol=pickle.HIGHEST_PROTOCOL)
        print(f"\nNormalized features saved to: {output_feature_file}")
    except Exception as e:
        print(f"Error saving file: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
